exports.seed = knex => knex('Persons')
  .del()
  .then(() => knex.batchInsert('Persons', [
    {
      fName: 'Michael',
      lName: 'Curtiz',
      nick: 'Miska',
      birthDate: '1886-12-24',
      info: 'Curtiz began acting in and then directing films in his native Hungary in 1912. After WWI, he continued his filmmaking career in Austria and Germany and into the early 1920s when he directed films in other countries in Europe. Moving to the US in 1926, he started making films in Hollywood for Warner Bros. and became thoroughly entrenched in the studio system. His films during the 1930s and \'40s encompassed nearly every genre imaginable and some, including Casablanca (1942) and Mildred Pierce (1945), are considered to be film classics. His brilliance waned in the 1950s when he made a number of mediocre films for studios other than Warner. He directed his last film in 1961, a year before his death at 74.',
    },
    {
      fName: 'Julius J.',
      lName: 'Epstein',
      nick: null,
      birthDate: '1909-08-22',
      info: 'Julius J. Epstein was born on August 22, 1909 in New York City, New York, USA. He was a writer and producer, known for Casablanca (1942), Reuben, Reuben (1983) and Pete \'n\' Tillie (1972). He was married to Ann Margot Laszlo and Frances Sage. He died on December 30, 2000 in Los Angeles, California, USA.',
    },
    {
      fName: 'Philip G.',
      lName: 'Epstein',
      nick: null,
      birthDate: '1909-08-22',
      info: `Twin brother of Julius J. Epstein.
        Graduated Penn State University [1931]
        Is the grandfather of Boston Red Sox general manager Theo Epstein (the youngest GM in baseball history, who built the 2004 team than won the first Red Sox World Series victory since 1918, reversing the so-called "curse of the Bambino")
        Is the father of novelist Leslie Epstein ("Pandaemonium", "San Remo Drive")
        Is the grandfather of Anya Epstein and her brother, Boston Red Sox general manager Theo Epstein (the youngest GM in baseball history, who built the 2004 team than won the first Red Sox World Series victory since 1918, reversing the so-called "curse of the Bambino").
        Epstein and brother Julius J. Epstein became the first twins to be awarded Oscars when they won in the writing category for Casablanca (1942).`,
    },
    {
      fName: 'Humphrey',
      lName: 'Bogart',
      nick: 'Bogie',
      birthDate: '1899-01-14',
      info: 'Humphrey DeForest Bogart was born in New York City, New York, to Maud Humphrey, a famed magazine illustrator and suffragette, and Belmont DeForest Bogart, a moderately wealthy surgeon (who was secretly addicted to opium). Bogart was educated at Trinity School, NYC, and was sent to Phillips Academy in Andover, Massachusetts, in preparation for medical studies at Yale. He was expelled from Phillips and joined the U.S. Naval Reserve. From 1920 to 1922, he managed a stage company owned by family friend William A. Brady (the father of actress Alice Brady), performing a variety of tasks at Brady\'s film studio in New York. He then began regular stage performances. Alexander Woollcott described his acting in a 1922 play as inadequate. In 1930, he gained a contract with Fox, his feature film debut in a ten-minute short, Broadway\'s Like That (1930), co-starring Ruth Etting and Joan Blondell. Fox released him after two years. After five years of stage and minor film roles, he had his breakthrough role in The Petrified Forest (1936) from Warner Bros. He won the part over Edward G. Robinson only after the star, Leslie Howard, threatened Warner Bros. that he would quit unless Bogart was given the key role of Duke Mantee, which he had played in the Broadway production with Howard. The film was a major success and led to a long-term contract with Warner Bros. From 1936 to 1940, Bogart appeared in 28 films, usually as a gangster, twice in Westerns and even a horror film. His landmark year was 1941 (often capitalizing on parts George Raft had stupidly rejected) with roles in classics such as High Sierra (1941) and as Sam Spade in one of his most fondly remembered films, The Maltese Falcon (1941). These were followed by Casablanca (1942), The Big Sleep (1946), and Key Largo (1948). Bogart, despite his erratic education, was incredibly well-read and he favored writers and intellectuals within his small circle of friends. In 1947, he joined wife Lauren Bacall and other actors protesting the House Un-American Activities Committee witch hunts. He also formed his own production company, and the next year made The Treasure of the Sierra Madre (1948). Bogie won the best actor Academy Award for The African Queen (1951) and was nominated for Casablanca (1942) and as Captain Queeg in The Caine Mutiny (1954), a film made when he was already seriously ill. He died in his sleep at his Hollywood home following surgeries and a battle with throat cancer.',
    },
    {
      fName: 'Ingrid',
      lName: 'Bergman',
      nick: null,
      birthDate: '1915-08-29',
      info: `Ingrid Bergman was one of the greatest actresses from Hollywood's lamented Golden Era. Her natural and unpretentious beauty and her immense acting talent made her one of the most celebrated figures in the history of American cinema. Bergman is also one of the most Oscar-awarded actresses, tied with Meryl Streep, both second only to Katharine Hepburn.
        Ingrid Bergman was born on August 29, 1915 in Stockholm, Sweden, to a German mother, Frieda Henrietta (Adler), and a Swedish father, Justus Samuel Bergman, an artist and photographer. Her mother died when she was only two and her father died when she was 12. She went to live with an elderly uncle.      
        The woman who would be one of the top stars in Hollywood in the 1940s had decided to become an actress after finishing her formal schooling. She had had a taste of acting at age 17 when she played an uncredited role of a girl standing in line in the Swedish film Landskamp (1932) in 1932 - not much of a beginning for a girl who would be known as "Sweden's illustrious gift to Hollywood." Her parents died when she was just a girl and the uncle she lived with didn't want to stand in the way of Ingrid's dream. The next year she enrolled at the Royal Dramatic Theatre School in Stockholm but decided that stage acting was not for her. It would be three more years before she would have another chance at a film. When she did, it was more than just a bit part. The film in question was The Count of the Old Town (1935), where she had a speaking part as Elsa Edlund. After several films that year that established her as a class actress, Ingrid appeared in Intermezzo (1936) as Anita Hoffman. Luckily for her, American producer David O. Selznick saw it and sent a representative from Selznick International Pictures to gain rights to the story and have Ingrid signed to a contract. Once signed, she came to California and starred in United Artists' 1939 remake of her 1936 film, Intermezzo: A Love Story (1939), reprising her original role. The film was a hit and so was Ingrid.
        Her beauty was unlike anything the movie industry had seen before and her acting was superb. Hollywood was about to find out that they had the most versatile actress the industry had ever seen. Here was a woman who truly cared about the craft she represented. The public fell in love with her. Ingrid was under contract to go back to Sweden to film Only One Night (1939) in 1939 and June Night (1940) in 1940. Back in the US she appeared in three films, all well-received. She made only one film in 1942, but it was the classic Casablanca (1942) opposite Humphrey Bogart.
        Ingrid was choosing her roles well. In 1943 she was nominated for an Academy Award for her role in For Whom the Bell Tolls (1943), the only film she made that year. The critics and public didn't forget her when she made Gaslight (1944) the following year--her role of Paula Alquist got her the Oscar for Best Actress. In 1945 Ingrid played in Spellbound (1945), Saratoga Trunk (1945) and The Bells of St. Mary's (1945), for which she received her third Oscar nomination for her role of Sister Benedict. She made no films in 1947, but bounced back with a fourth nomination for Joan of Arc (1948). In 1949 she went to Italy to film Stromboli, terra di Dio (1950), directed by Roberto Rossellini. She fell in love with him and left her husband, Dr. Peter Lindstrom, and daughter, Pia Lindström. America's "moral guardians" in the press and the pulpits were outraged. She was pregnant and decided to remain in Italy, where her son was born. In 1952 Ingrid had twins, Isotta and Isabella Rossellini, who became an outstanding actress in her own right, as did Pia.
        Ingrid continued to make films in Italy and finally returned to Hollywood in 1956 in the title role in Anastasia (1956), which was filmed in England. For this she won her second Academy Award. She had scarcely missed a beat. Ingrid continued to bounce between Europe and the US making movies, and fine ones at that. A film with Ingrid Bergman was sure to be a quality production. In her final big-screen performance in 1978's Autumn Sonata (1978) she had her final Academy Award nomination. Though she didn't win, many felt it was the most sterling performance of her career. Ingrid retired, but not before she gave an outstanding performance in the mini-series A Woman Called Golda (1982), a film about Israeli prime minister Golda Meir. For this she won an Emmy Award as Best Actress, but, unfortunately, she did not live to see the fruits of her labor.
        Ingrid died from cancer on August 29, 1982, her 67th birthday, in London, England.`,
    },
    {
      fName: 'Paul',
      lName: 'Henreid',
      nick: null,
      birthDate: '1908-01-10',
      info: `Paul Henreid was born Paul Georg Julius Freiherr von Hernreid Ritter von Wasel-Waldingau in Trieste, in the Austro-Hungarian Empire. He was the son of Marie Luise Heilig (Lendecke) and Baron Karl Alphons Hernreid. His father was an aristocratic banker, who was born to a Jewish family whose surname was changed from Hirsch to Hernreid.
        Paul grew up in Vienna and studied at the prestigious Maria Theresa Academy (graduating in 1927) and the Institute of Graphic Arts. For four years, he worked as translator and book designer for a publishing outfit run by Otto Preminger, while training to be an actor at night. Preminger was also a protégé (and managing director) of Max Reinhardt. After attending one of Henreid's acting school performances, Preminger introduced him to the famous stage director and this led to a contract. In 1933, Paul made his debut at the Reinhardt Theatre in "Faust". He subsequently had several leading roles on the stage and appeared in a couple of Austrian films. Paul, like his character Victor Laszlo in Casablanca (1942), was avidly anti-fascist. He accordingly left continental Europe and went to London in 1935, first appearing on stage as Prince Albert in "Victoria the Great" two years later.
        Henreid made his English-speaking motion picture debut in the popular drama Goodbye, Mr. Chips (1939), as the sympathetic German master Max Staefel, who proves to be Chipping's truest friend and ally. After that, however, he became incongruously typecast as Nazi henchmen in Mad Men of Europe (1940) and Night Train to Munich (1940). That year, he moved to the United States (becoming a citizen the following year) and quickly established himself on Broadway with "Flight to the West", as a Ribbentrop-type Nazi consul. His powerful performance led to radio work in the serial "Joyce Jordan-Girl Interne" and a film contract with RKO in 1941.
        This marked a turning point in Paul Henreid's career. He finally escaped the stereotypical Teutonic image and began to play heroic or romantic leads, his first being Joan of Paris (1942), opposite Michèle Morgan, as French RAF pilot Paul Lavallier. Significantly, his next film, Now, Voyager (1942), defined his new screen persona: debonnaire, cultured and genteel, lighting two cigarettes simultaneously, then passing one to Bette Davis. According to Henreid, this legendary (and later often lampooned) scene was almost cut from the film because the director, Irving Rapper, had concerns about it. Next came "Casablanca", where Henreid played the idealistic, sensitive patriot Victor Laszlo; the poorly received Bronte sisters biopic Devotion (1946), as an Irish priest; and a stalwart performance as a Polish count and Ida Lupino's love interest, In Our Time (1944).
        After several dull romantic leads, Henreid reinvented himself yet again. He played a memorably athletic and lively Dutch pirate, the 'Barracuda', in RKO's colourful swashbuckler The Spanish Main (1945). Another of his best later performances was as a sadistic South African commandant in the underrated film noir Rope of Sand (1949), which re-united him with his former "Casablanca" co-stars Peter Lorre and Claude Rains. After the Arabian Technicolor adventure, Thief of Damascus (1952), Henreid's star began to fade. His last noteworthy appearance during the fifties was as an itinerant magician in the oriental extravaganza Siren of Bagdad (1953) . The most memorable of several in-jokes, had Henreid lighting two hookahs (water pipes) for one of his harem girls, spoofing his famous scene from "Now, Voyager".
        Outspoken in his opposition to McCarthyism and adhering to his rights under the First Amendment, he was subsequently blacklisted as a "communist sympathizer" by the House Committee on Un- American Activities. In spite of the damage this did to his career, he re-emerged as a director of second features and television episodes for Screen Gems, Desilu and other companies. In 1957, Alfred Hitchcock (in defiance of the blacklist) hired him to direct several episodes of Alfred Hitchcock Presents (1955). Towards the end of his career, Paul Henreid directed his former "Now, Voyager" co-star Bette Davis in the camp melodrama Dead Ringer (1964) and toured with Agnes Moorehead on stage in a short-lived revival of "Don Juan in Hell"(1972- 73). Henreid died of pneumonia in a Santa Monica hospital in April 1992, after having suffered a stroke. He has the distinction of having not just one but two stars on the Hollywood Walk of Fame, one for his films, and one for his television work.`,
    },
    {
      fName: 'Hal B.',
      lName: 'Wallis',
      nick: null,
      birthDate: '1899-09-14',
      info: 'Legendary producer Hal B. Wallis was born in Chicago and moved to Los Angeles when he was in his early 20s. He got a job managing a theater owned by Warner Bros., and his success at the job caught the eye of studio head Jack L. Warner, who gave him a job in the studio\'s publicity department. Within a few months Wallis had worked his way up to head of the department. He was named studio manager in 1928 and production manager shortly thereafter, but was pushed aside by another legendary producer, future 20th Century-Fox studio head Darryl F. Zanuck. In 1933 Zanuck left Warner and Wallis moved back to his old position. He oversaw the production of many of Warners\' most famous films, including Little Caesar (1931), I Am a Fugitive from a Chain Gang (1932), Captain Blood (1935), The Adventures of Robin Hood (1938) and Casablanca (1942). In 1944 Wallis left Warner and formed his own production company, and achieved even more success, being responsible for such films as The Rose Tattoo (1955), Becket (1964), and a string of Elvis Presley movies, most of which were economically produced and all of which made a fortune. Wallis\' last picture was the John Wayne western Rooster Cogburn (1975).',
    },
    {
      fName: 'Jack L.',
      lName: 'Warner',
      nick: 'Mr. Warner',
      birthDate: '1892-08-02',
      info: 'With his brothers Harry M. Warner, Albert Warner, and Sam Warner, he founded Warner Bros. Pictures Inc. in 1923. They released the first motion picture with synchronized sound, The Jazz Singer (1927) with Al Jolson. In the 1930s they gave employment to a parade of stars, including Bette Davis, Errol Flynn and Paul Muni, as well as James Cagney, Edward G. Robinson, and a man whose star would eventually rise in the 1940s, Humphrey Bogart. Decades later, the firm\'s successor, Warner Communications Inc., merged with Time Inc. to become Time Warner Inc., the world\'s largest media and entertainment company.',
    },
    {
      fName: 'Max',
      lName: 'Steiner',
      nick: 'Mr. Warner',
      birthDate: '1888-05-10',
      info: `Austrian composer who achieved legendary status as the creator of hundreds of classic American film scores. As a child he was astonishingly musically gifted, composing complex works as a teenager and completing the course of study at Vienna's Hochschule fuer Musik und Darstellende Kunst in only one year, at the age of sixteen. He studied under Gustav Mahler and, before the age of twenty, made his living as a conductor and as composer of works for the theater, the concert hall, and vaudeville. After a brief sojourn in Britian, Steiner moved to the USA in the same wave as fellow film composer Erich Wolfgang Korngold and quickly became a sought-after orchestrator and conductor on Broadway, bringing the Western classical tradition in which he had been raised to mainstream audiences.      He was soon snatched up by the film studios with the advent of sound and helped the fledgling talkies become musically sophisticated within a brief few years. He was one of the first to fully integrate the musical score with the images on-screen and to score individual scenes for their content and create leitmotifs for individual characters, as opposed to simply providing vaguely appropriate mood music, as evidenced in King Kong (1933), which set the standard for American film music for years to come.
        From the 1930s to the 1960s, he was one of the most respected, innovative, and brilliant composers of American film music, creating a truly staggering number of exceptional scores for films of all types. He was nominated for Academy Awards for his scores eighteen times and won three times. Years after his death in 1971, he remains one of the giants of motion picture history, and his music still thrives.`,
    },

    {
      fName: 'John',
      lName: 'Woo',
      nick: null,
      birthDate: '1946-09-22',
      info: 'Born in southern China, John Woo grew up in Hong Kong, where he began his film career as an assistant director in 1969, working for Shaw Brothers Studios. He directed his first feature in 1973 and has been a prolific director ever since, working in a wide variety of genres before A Better Tomorrow (1986) established his reputation as a master stylist specializing in ultra-violent gangster films and thrillers, with hugely elaborate action scenes shot with breathtaking panache. After gaining a cult reputation in the US with The Killer (1989), Woo was offered a Hollywood contract. He now works in the US.',
    },
    {
      fName: 'Mike',
      lName: 'Werb',
      nick: null,
      birthDate: null,
      info: `A Los Angeles native, Mike Werb received his undergraduate degrees from Stanford, where he majored in one thing after another. He put his costly education to use by joining a New Wave garage band that never left the garage. Turning to writing, he began a burlesque climb up the well-greased Hollywood ladder by entering the UCLA Master's program in screenwriting. He has since worked for every major studio.
        Mike's big break was writing the screenplay for the Jim Carrey comedy "The Mask," but he also embraces his other produced credits, including "Darkman 3: Die, Darkman, Die!," and the giant-rats-attack-a-college-campus epic "Gnaw: The Food of the Gods, Part 2."
        Mike co-wrote and co-produced (with Michael Colleary) the action-thriller "Face/Off," directed by John Woo and starring John Travolta and Nicolas Cage. The New York Times lauded the Oscar-nominated film as "one the 1,000 greatest movies of all time," and Face/Off won the 1997 Best Screenplay statuette at the 24th annual Saturn Awards.
        21st century accomplishments include being one of six credited screenwriters on "Lara Croft: Tomb Raider" starring Angelina Jolie, and the WB's flashy flop TV series "Tarzan" starring Travis Fimmel's abs. Werb and Colleary also worked intimately with Arnold Schwarzenegger on "Collateral Damage," his last major motion picture before becoming Governor of California.
        Recent film credits include the well-reviewed animated hit "Curious George" (Universal/Imagine) and the family comedy "Firehouse Dog" (New Regency/Fox). Werb and Colleary are developing "Prophets of the Ghost Ants" with author Clark Carlton, Lawrence Bender/A Band Apart and director Conrad Vernon ("Monsters v. Aliens").
        Mike also wrote the nano-tech action pilot "Flyswatters" for the SyFy Channel which he will executive produce with Darren Star ("Sex and the City") should it ever go into production.
        He is currently working on "Unnatural History" -- a live-action-adventure series for Warner Horizon and the Cartoon Network.
        Mike is a member of the Academy of Motion Picture Arts and Sciences, the Writers Guild of America and a nominating-committee member of the Academy of Science Fiction, Fantasy and Horror.`,
    },
    {
      fName: 'Micheal',
      lName: 'Colleary',
      nick: null,
      birthDate: null,
      info: 'Michael Colleary is a writer and producer, known for Face/Off (1997), Lara Croft: Tomb Raider (2001) and Unnatural History (2010).',
    },
    {
      fName: 'Terence',
      lName: 'Chang',
      nick: null,
      birthDate: null,
      info: 'Terence Chang is a producer, known for Paycheck (2003), Face/Off (1997) and Warriors of the Rainbow: Seediq Bale I (2011).',
    },
    {
      fName: 'John',
      lName: 'Powell',
      nick: null,
      birthDate: '1963-09-18',
      info: 'John Powell was born on September 18, 1963 in London, England. He is a composer, known for How to Train Your Dragon (2010), Rio (2011) and The Bourne Identity (2002). He was previously married to Melinda Lerner.',
    },
    {
      fName: 'John',
      lName: 'Travolta',
      nick: null,
      birthDate: '1954-02-18',
      info: `John Joseph Travolta was born in Englewood, New Jersey, one of six children of Helen Travolta (née Helen Cecilia Burke) and Salvatore/Samuel J. Travolta. His father was of Italian descent and his mother was of Irish ancestry. His father owned a tire repair shop called Travolta Tires in Hillsdale, NJ. Travolta started acting appearing in a local production of "Who'll Save the Plowboy?". His mother, herself an actress and dancer, enrolled him in a drama school in New York, where he studied voice, dancing and acting. He decided to combine all three of these skills and become a musical comedy performer. At 16 he landed his first professional job in a summer stock production of the musical "Bye Bye Birdie". He quit school at 16 and moved to New York, and worked regularly in summer stock and on television commercials. When work became scarce in New York, he went to Hollywood and appeared in minor roles in several series. A role in the national touring company of the hit 1950s musical "Grease" brought him back to New York. An opening in the New York production of "Grease" gave him his first Broadway role at age 18. After "Grease", he became a member of the company of the Broadway show "Over Here", which starred The Andrews Sisters. After ten months in "Over Here", he decided to try Hollywood once again. Once back in Hollywood, he had little trouble getting roles in numerous television shows. He was seen on The Rookies (1972), Emergency! (1972) and Medical Center (1969) and also made a movie, The Devil's Rain (1975), which was shot in New Mexico. The day he returned to Hollywood from New Mexico, he was called to an audition for a new situation comedy series ABC was planning to produce called Welcome Back, Kotter (1975). He got the part of Vinnie Barbarino and the series went on the air during the 1975 fall season.
        He starred in a number of monumental films, earning his first Oscar and Golden Globe nominations for his role in the blockbuster Saturday Night Fever (1977), which launched the disco phenomenon in the 1970s. He went on to star in the big-screen version of the long-running musical Grease (1978) and the wildly successful Urban Cowboy (1980), which also influenced trends in popular culture. Additional film credits include the Brian De Palma thrillers Carrie (1976) and Blow Out (1981), as well as Amy Heckerling's hit comedy Look Who's Talking (1989) and Nora Ephron's comic hit Michael (1996). Travolta starred in Phenomenon (1996) and took an equally distinctive turn as an action star in John Woo's top-grossing Broken Arrow (1996). He also starred in the classic Face/Off (1997) opposite Nicolas Cage, and The General's Daughter (1999), co-starring Madeleine Stowe. In 2005, Travolta reprised the role of ultra cool Chili Palmer in the Get Shorty (1995) sequel Be Cool (2005). In addition, he starred opposite Scarlett Johansson in the critically-acclaimed independent feature film A Love Song for Bobby Long (2004), which was screened at the Venice Film Festival, where both Travolta and the films won rave reviews. In February 2011, John was honored by Europe's leading weekly program magazine HORZU, with the prestigious Golden Camera Award for "Best Actor International" in Berlin, Germany. Other recent feature film credits include box-office hit-comedy "Wild Hogs", the action-thriller Ladder 49 (2004), the movie version of the successful comic book The Punisher (2004), the drama Basic (2003), the psychological thriller Domestic Disturbance (2001), the hit action picture Swordfish (2001), the infamous sci-fi movie Battlefield Earth (2000), based upon the best-selling novel by L. Ron Hubbard, and Lonely Hearts (2006).
        Travolta has been honored twice with Academy Award nominations, the latest for his riveting portrayal of a philosophical hit-man in Quentin Tarantino's Pulp Fiction (1994). He also received BAFTA and Golden Globe nominations for this highly-acclaimed role and was named Best Actor by the Los Angeles Film Critics Association, among other distinguished awards. Travolta garnered further praise as a Mafioso-turned-movie producer in the comedy sensation Get Shorty (1995), winning the Golden Globe Award for Best Actor in a Motion Picture, Musical or Comedy. In 1998, Travolta was honored by the British Academy of Film and Television Arts with the Britanna Award: and in that same year he received the Lifetime Achievement Award at the Chicago Film Festival. Travolta also won the prestigious Alan J. Pakula Award from the US Broadcast Critics Association for his performance in A Civil Action (1998), based on the best-selling book and directed by Steven Zaillian. He was nominated again for a Golden Globe for his performance in Primary Colors (1998), directed by Mike Nichols and co-starring Emma Thompson and Billy Bob Thornton, and in 2008, he received his sixth Golden Globe nomination for his role as "Edna Turnblad" in the big-screen, box-office hit, Hairspray (2007). As a result of this performance, the Chicago Film Critics and the Santa Barbara Film Festival decided to recognize Travolta with a Lifetime Achievement Award for his role.
        In addition, Travolta starred opposite Denzel Washington in Tony Scott's remake The Taking of Pelham 123 (2009), and he provided the voice of the lead character in Walt Disney Pictures' animated hit Bolt (2008), which was nominated for a 2009 Academy Award for Best Animated Feature Film and a Golden Globe for Best Animated Film, in addition to Best Song for John and Miley Cyrus' duet titled, "I Thought I Lost You".
        Next, Travolta starred in Walt Disney Pictures' Old Dogs (2009), along with Robin Williams, Kelly Preston and Ella Bleu Travolta, followed by the action thriller З Парижу з любов'ю (2010), starring opposite Jonathan Rhys Meyers. In 2012, John starred alongside Taylor Kitsch, Blake Lively, Aaron Taylor-Johnson, Benicio Del Toro, Salma Hayek, Emile Hirsch and Demián Bichir in Oliver Stone's, Savages (2012). The film was based on Don Winslow's best-selling crime novel that was named one of The New York Times' Top 10 Books of 2010. John was most recently seen in Killing Season (2013), co-starring Robert De Niro, and directed by Mark Steven Johnson. John recently completed production on the Boston-based film, The Forger (2014), alongside Academy Award winner Christopher Plummer and Critic's Choice nominee Tye Sheridan. John plays a second-generation petty thief who arranges to get out of prison to spend time with his ailing son (Sheridan) by taking on a job with his father (Plummer) to pay back the syndicate that arranged his release. John has received 2 prestigious aviation awards: in 2003, the American Institute of Aeronautics and Astronautics Foundation Award for Excellence for his efforts to promote commercial flying, and, in 2007, The Living Legends Ambassador of Aviation award.
        John holds 11 jet licenses: 747, 707, Gulfstream II, Lear 24, Hawker 1251A, Eclipse Jet, Vampire Jet, Canadair CL-141 Jet, Soko Jet, Citation ISP and Challenger. Travolta is the Qantas Airways Global Goodwill "Ambassador-at-Large" and piloted the original Qantas 707 during "Spirit of Friendship" global tour in July/August 2002. John is also a business aircraft brand ambassador for Learjet, Challenger and Global jets for the world's leading business aircraft manufacturer, Bombardier. John flew the 707 to New Orleans after the 2005 hurricane disaster bringing food and medical supplies, and in 2010, again flew the 707, this time to Haiti after the earthquake, carrying supplies, doctors and volunteers.
        John, along with his wife, actress Kelly Preston, are also very involved in their charity, The Jett Travolta Foundation, which raises money for children with educational needs.`,
    },
    {
      fName: 'Nicolas',
      lName: 'Cage',
      nick: 'Nick',
      birthDate: '1964-01-07',
      info: `Nicolas Cage was born Nicolas Kim Coppola in Long Beach, California, the son of comparative literature professor August Coppola (whose brother is director Francis Ford Coppola) and dancer/choreographer Joy Vogelsang. He is of Italian (father) and Polish, German, and English (mother) descent. Cage changed his name early in his career to make his own reputation, succeeding brilliantly with a host of classic, quirky roles by the late 1980s.
        Initially studying theatre at Beverly Hills High School (though he dropped out at seventeen), he secured a bit part in Fast Times at Ridgemont High (1982) -- most of which was cut, dashing his hopes and leading to a job selling popcorn at the Fairfax Theater, thinking that would be the only route to a movie career. But a job reading lines with actors auditioning for uncle Francis' Rumble Fish (1983) landed him a role in that film, followed by the punk-rocker in Valley Girl (1983), which was released first and truly launched his career.
        His one-time passion for method acting reached a personal limit when he smashed a street-vendor's remote-control car to achieve the sense of rage needed for his gangster character in The Cotton Club (1984).
        In his early 20s, he dated Jenny Wright for two years and later linked to Uma Thurman. After a relationship of several years with Christina Fulton, a model, they split amicably and share custody of a son, Weston Cage (b.1992). In 2004, he married Alice Kim Cage, with whom he has a son.`,
    },
    {
      fName: 'Alfred',
      lName: 'Hitchcock',
      nick: null,
      birthDate: '1899-08-13',
      info: `Alfred Joseph Hitchcock was born in Leytonstone, Essex, England. He was the son of Emma Jane (Whelan; 1863 - 1942) and East End greengrocer William Hitchcock (1862 - 1914). His parents were both of half English and half Irish ancestry. He had two older siblings, William Hitchcock (born 1890) and Eileen Hitchcock (born 1892). Raised as a strict Catholic and attending Saint Ignatius College, a school run by Jesuits, Hitch had very much of a regular upbringing. His first job outside of the family business was in 1915 as an estimator for the Henley Telegraph and Cable Company. His interest in movies began at around this time, frequently visiting the cinema and reading US trade journals.
        It was around 1920 when Hitchcock joined the film industry. He started off drawing the sets (he was a very skilled artist). It was there that he met Alma Reville, though they never really spoke to each other. It was only after the director for Always Tell Your Wife (1923) fell ill and Hitchcock was named director to complete the film that he and Reville began to collaborate. Hitchcock had his first real crack at directing a film, start to finish, in 1923 when he was hired to direct the film Number 13 (1922), though the production wasn't completed due to the studio's closure (he later remade it as a sound film). Hitchcock didn't give up then. He directed The Pleasure Garden (1925), a British/German production, which was very popular. Hitchcock made his first trademark film in 1927, The Lodger (1927) . In the same year, on the 2nd of December, Hitchcock married Alma Reville. They had one child, _Patricia Hitchcock_ who was born on July 7th, 1928. His success followed when he made a number of films in Britain such as The Lady Vanishes (1938) and Jamaica Inn (1939), some of which also gained him fame in the USA.
        In 1940, the Hitchcock family moved to Hollywood, where the producer _David O. Selznick_had hired him to direct an adaptation of 'Daphne du Maurier''s Rebecca (1940). After Saboteur (1942), as his fame as a director grew, film companies began to refer to his films as 'Alfred Hitchcock's', for example Alfred Hitcock's Psycho (1960), Alfred Hitchcock's Family Plot (1976), Alfred Hitchcock's Frenzy (1972).
        Hitchcock was a master of pure cinema who almost never failed to reconcile aesthetics with the demands of the box-office.
        During the making of Frenzy (1972), Hitchcock's wife Alma suffered a paralyzing stroke which made her unable to walk very well. On March 7, 1979, Hitchcock was awarded the AFI Life Achievement Award, where he said: "I beg permission to mention by name only four people who have given me the most affection, appreciation, and encouragement, and constant collaboration. The first of the four is a film editor, the second is a scriptwriter, the third is the mother of my daughter Pat, and the fourth is as fine a cook as ever performed miracles in a domestic kitchen and their names are Alma Reville." By this time, he was ill with angina and his kidneys had already started to fail. He had started to write a screenplay with _Ernest Lehman_ called The Short Night but he fired Lehman and hired young writer David Freeman to rewrite the script. Due to Hitchcock's failing health the film was never made, but Freeman published the script after Hitchcock's death. In late 1979, Hitchcock was knighted, making him Sir Alfred Hitchcock. On the 29th April 1980, 9:17AM, he died peacefully in his sleep due to renal failure. His funeral was held in the Church of Good Shepherd in Beverly Hills. Father Thomas Sullivan led the service with over 600 people attended the service, among them were Mel Brooks (director of High Anxiety (1977), a comedy tribute to Hitchcock and his films), Louis Jourdan, Karl Malden, Tippi Hedren, Janet Leigh and François Truffaut.`,
    },
    {
      fName: 'Ben',
      lName: 'Hetch',
      nick: 'Benny, Lester Barlow',
      birthDate: '1894-04-18',
      info: `Ben Hecht, one of Hollywood's and Broadway's greatest writers, won an Oscar for best original story for Underworld (1927) at the first Academy Awards in 1929 and had a hand in the writing of many classic films. He was nominated five more times for the best writing Oscar, winning (along with writing partner and friend Charles MacArthur, with whom he wrote the classic play "The Front Page") for The Scoundrel (1935) (the other nominations were for Viva Villa! (1934) in 1935, Wuthering Heights (1939) (shared with MacArthur), Angels Over Broadway (1940) and Notorious (1946), the latter two for best original screenplay). Hecht wrote fast and wrote well, and he was called upon by many producers as a highly paid script doctor. He was paid $10,000 by producer David O. Selznick for a fast doctoring of the Gone with the Wind (1939) script, for which he received no credit and for which Sidney Howard won an Oscar, beating out Hecht and MacArthur's Wuthering Heights (1939) script.
        Born on February 28, 1894, Hecht made his name as a Chicago newspaperman during the heady days of cutthroat competition among newspapers and journalists. As a reporter for the Chicago Daily News, he wrote the column "1001 Afternoons in Chicago" and broke the "Ragged Stranger Murder Case" story, which led to the conviction and execution of Army war hero Carl Wanderer for the murder of his pregnant wife in 1921. The newspaper business, which he and MacArthur famously parodied in "The Front Page", was a good training ground for a screenwriter, as he had to write vivid prose and had to write quickly.
        While in New York in 1926 he received a telegram from friend Herman J. Mankiewicz, who had recently arrived in Hollywood. The telegram read: "Millions are to be grabbed out here and your only competition is idiots. Don't let this get around." Hecht moved to Hollywood, winding up at Paramount, working uncredited on the script for Lewis Milestone's adaptation of Ring Lardner's story The New Klondike (1926), starring silent superstar Thomas Meighan. However, it was his script for Josef von Sternberg's seminal gangster picture Underworld (1927) that got him noticed. From then until the 1960s, he was arguably the most famous, if not the highest paid, screenwriter of his time.
        As a playwright, novelist and short-story writer, Hecht always denigrated writing for the movies, but it is for such films as Scarface (1932) and Nothing Sacred (1937) as well The Front Page (1931), based on his play of the same name, for which he is best remembered.
        He died on April 18, 1964, in New York City from thrombosis. He was 70 years old.`,
    },
    {
      fName: 'Roy',
      lName: 'Webb',
      nick: 'Benny, Lester Barlow',
      birthDate: '1982-12-10',
      info: `Trained in classical music at Columbia University, Webb worked on Broadway by the time he was in his mid-20's, not only composing incidental music, but co-writing original plays with his older brother, the director Kenneth S. Webb. By 1923, he worked as conductor/arranger on hit shows like "Music Box Revue" and "Stepping Stones". Two years later, a collaboration with his illustrious peer Max Steiner led to a lasting friendship, as well as (by his own admission) profoundly influencing his own future career as a composer. At the end of the decade, Steiner, then head of the music department at RKO, persuaded Webb to accept an assignment in Hollywood, scoring the musical Rio Rita (1929).
        Steiner remained in charge until his departure in 1935, when Webb effectively took his place, remaining a fixture at RKO until 1955. He often worked in conjunction with Bernard Herrmann and C. Bakaleinikoff, supervising, conducting and composing scores for literally hundreds of films. As a composer, his style was somewhat akin to that of Herbert Stothart, in that it was more subtle, less overtly dramatic, yet still perfectly integrated with the action, or imperceptibly underscoring the dialogue. A good example is the romantic violin-laden score for the sentimental drama The Enchanted Cottage (1945). The piano concerto from this film was performed later that year at the Hollywood Bowl.
        Better still, were his understated, eerily effective horror themes, setting the mood for the films of Val Lewton, of which Cat People (1942) and The Body Snatcher (1945) are absolute standouts. Webb's other noteworthy contribution was in the field of thrillers and films noir, notably The Spiral Staircase (1946), Notorious (1946) and Out of the Past (1947). After RKO wound down, Webb free-lanced for several years, working variously at Warners, Paramount and for John Wayne's Batjac Productions. Though his entire collection of manuscripts was sadly lost in a house fire, copies of his scores from the RKO vaults have been preserved at UCLA.`,
    },
    {
      fName: 'Cary',
      lName: 'Grant',
      nick: null,
      birthDate: '1904-01-18',
      info: `Once told by an interviewer, "Everybody would like to be Cary Grant", Grant is said to have replied, "So would I."
        Cary Grant was born Archibald Alexander Leach on January 18, 1904 in Horfield, Bristol, England, to Elsie Maria (Kingdon) and Elias James Leach, who worked in a factory. His early years in Bristol would have been an ordinary lower-middle-class childhood, except for one extraordinary event. At age nine, he came home from school one day and was told his mother had gone off to a seaside resort. However, the real truth was that she had been placed in a mental institution, where she would remain for years, and he was never told about it (he would not see his mother again until he was in his late 20s).
        He left school at age 14, lying about his age and forging his father's signature on a letter to join Bob Pender's troupe of knockabout comedians. He learned pantomime as well as acrobatics as he toured with the Pender troupe in the English provinces, picked up a Cockney accent in the music halls in London, and then in July 1920, was one of the eight Pender boys selected to go to the United States. Their show on Broadway, "Good Times", ran for 456 performances, giving Grant time to acclimatize. He would stay in America. Mae West wanted Grant for She Done Him Wrong (1933) because she saw his combination of virility, sexuality and the aura and bearing of a gentleman. Grant was young enough to begin the new career of fatherhood when he stopped making movies at age 62.
        One biographer said Grant was alienated by the new realism in the film industry. In the 1950s and early 1960s, he had invented a man-of-the-world persona and a style - "high comedy with polished words". In To Catch a Thief (1955), he and Grace Kelly were allowed to improvise some of the dialogue. They knew what the director, Alfred Hitchcock, wanted to do with a scene, they rehearsed it, put in some clever double entendres that got past the censors, and then the scene was filmed. His biggest box-office success was another Hitchcock 1950s film, North by Northwest (1959) made with Eva Marie Saint since Kelly was by that time Princess of Monaco.
        Although Grant retired from the screen, he remained active. He accepted a position on the board of directors at Faberge. By all accounts this position was not honorary, as some had assumed. Grant regularly attended meetings and traveled internationally to support them. The position also permitted use of a private plane, which Grant could use to fly to see his daughter wherever her mother Dyan Cannon, was working. He later joined the boards of Hollywood Park, the Academy of Magical Arts (The Magic Castle - Hollywood, California), Western Airlines (acquired by Delta Airlines in 1987) and MGM.
        Grant expressed no interest in making a career comeback. He was in good health until almost the end of his life, when he suffered a mild stroke in October 1984. In his last years, he undertook tours of the United States in a one-man-show, "A Conversation with Cary Grant", in which he would show clips from his films and answer audience questions. On November 29, 1986, Cary Grant died at age 82 of a cerebral hemorrhage in Davenport, Iowa.
        In 1999, the American Film Institute named Grant the second male star of Golden Age of Hollywood cinema (after Humphrey Bogart). Grant was known for comedic and dramatic roles; his best-known films include Bringing Up Baby (1938), The Philadelphia Story (1940), His Girl Friday (1940), Arsenic and Old Lace (1944), Notorious (1946), An Affair to Remember (1957), North by Northwest (1959) and Charade (1963).`,
    },
    {
      fName: 'Michael',
      lName: 'Bay',
      nick: null,
      birthDate: '1965-02-17',
      info: 'A graduate of Wesleyan University, Michael Bay spent his 20s working on advertisements and music videos. His first projects after film school were in the music video business. He created music videos for Tina Turner, Meat Loaf, Lionel Richie, Wilson Phillips, Donny Osmond and Divinyls. His work won him recognition and a number of MTV award nominations. He also filmed advertisements for Nike, Reebok, Coca-Cola, Budweiser and Miller Lite. He won the Grand Prix Clio for Commercial of the Year for his "Got Milk/Aaron Burr" commercial. At Cannes, he has won the Gold Lion for The Best Beer campaign for Miller Lite, as well as the Silver for "Got Milk". In 1995, Bay was honored by the Directors Guild of America as Commercial Director of the Year. That same year, he also directed his first feature film, Bad Boys (1995), starring Will Smith and Martin Lawrence, which grossed more than $160 million, worldwide. His follow-up film, The Rock (1996), starring Sean Connery and Nicolas Cage, was also hugely successful, making Bay the director du jour.',
    },
    {
      fName: 'David',
      lName: 'Weisberg',
      nick: null,
      birthDate: null,
      info: 'David Weisberg is a writer and actor, known for Criminal (2016), The Rock (1996) and Double Jeopardy (1999).',
    },
    {
      fName: 'Kenny',
      lName: 'Bates',
      nick: null,
      birthDate: null,
      info: 'Kenny Bates is known for his work on Pearl Harbor (2001), Transformers: Dark of the Moon (2011) and The Island (2005).',
    },
    {
      fName: 'Jerry',
      lName: 'Bruckheimer',
      nick: 'Mr. Blockbuster',
      birthDate: '1943-09-21',
      info: 'Jerry Bruckheimer was born on September 21, 1943 in Detroit, Michigan, USA as Jerome Leon Bruckheimer. He is a producer, known for Armageddon (1998), Pirates of the Caribbean: At World\'s End (2007) and Pirates of the Caribbean: Dead Mans Chest (2006). He is married to Linda Bruckheimer. He was previously married to Bonnie Bruckheimer.',
    },
    {
      fName: 'Nick',
      lName: 'Glennie-Smith',
      nick: null,
      birthDate: '1951-10-03',
      info: 'Nick Glennie-Smith was born on October 3, 1951 in London, England. He is known for his work on The Rock (1996), We Were Soldiers (2002) and Людина в залiзнiй масцi (1998). He is married to Jan Glennie-Smith. They have four children.',
    },
    {
      fName: 'Sean',
      lName: 'Connery',
      nick: 'Big Tam',
      birthDate: '1930-08-25',
      info: `Sean Connery is best known for portraying the character James Bond, starring in seven Bond films between 1962 and 1983. In 1988, Connery won the Academy Award for Best Supporting Actor for his role in The Untouchables (1987). His film career also includes such films as Marnie (1964), The Name of the Rose (1986), The League of Extraordinary Gentlemen (2003), Indiana Jones and the Last Crusade (1989), The Hunt for Red October (1990), Highlander (1986), Murder on the Orient Express (1974), DragonHeart (1996) and The Rock (1996). Connery has been polled as "The Greatest Living Scot" and "Scotland's Greatest Living National Treasure". In 1989, he was proclaimed "Sexiest Man Alive" by People magazine, and in 1999, at age 69, he was voted "Sexiest Man of the Century".
        Thomas Sean Connery was born on August 25, 1930 in Fountainbridge, Edinburgh, Scotland. His mother, Euphemia McBain (née McLean), was a cleaning lady, and his father, Joseph Connery, was a factory worker and truck driver. He has a brother, Neil Connery, who works as a plasterer in Edinburgh. He is of Irish and Scottish descent. Before going into acting, Sean had many different jobs, such as a milkman, lorry driver, a laborer, artist's model for the Edinburgh College of Art, coffin polisher and bodybuilder. He also joined the Royal Navy, but was later discharged because of medical problems. At the age of 23, he had a choice between becoming a professional footballer or an actor, and even though he showed much promise in the sport, he chose acting and said it was one of his more intelligent moves.
        No Road Back (1957) was Sean's first major movie role, and it followed by several Tv-movies such as Anna Christie (1957), Macbeth (1961) and Anna Karenina (1961) and guest appearances on TV-series, and also films such as Hell Drivers (1957), Another Time, Another Place (1958), Darby O'Gill and the Little People (1959), The Frightened City (1961). In 1962 he appeared in The Longest Day (1962) with a host of other stars.
        Connery's breakthrough came in the role of secret agent James Bond. He was reluctant to commit to a film series, but understood that if the films succeeded his career would greatly benefit. He played the character in the first five Bond films: Dr. No (1962), From Russia with Love (1963), Goldfinger (1964), Thunderball (1965), and You Only Live Twice (1967) - then appeared again as Bond in Diamonds Are Forever (1971) and Never Say Never Again (1983). All seven films were commercially successful. James Bond, as portrayed by Connery, was selected as the third-greatest hero in cinema history by the American Film Institute. Connery's selection for the role of James Bond owed a lot to Dana Broccoli, wife of producer "Cubby" Broccoli, who is reputed to have been instrumental in persuading her husband that Connery was the right man. James Bond's creator, Ian Fleming, originally doubted Connery's casting, saying, "He's not what I envisioned of James Bond looks", and "I'm looking for Commander Bond and not an overgrown stunt-man," adding that Connery (muscular, 6' 2", and a Scot) was unrefined. Fleming's girlfriend told him that Connery had the requisite sexual charisma, and Fleming changed his mind after the successful Dr. No (1962) premiere. He was so impressed, he created a half-Scottish, half-Swiss heritage for Bond in the later novels. Connery's portrayal of Bond owes much to stylistic tutelage from director Terence Young, polishing the actor while using his physical grace and presence for the action. Lois Maxwell, who played Miss Moneypenny, related that, "Terence took Sean under his wing. He took him to dinner, showed him how to walk, how to talk, even how to eat." The tutoring was successful; Connery received thousands of fan letters a week, and the actor became one of the great male sex symbols of film. During the filming of Thunderball (1965), Connery's life was in danger in the sequence with the sharks in Emilio Largo's pool. He had been concerned about this threat when he read the script. Connery insisted that Ken Adam build a special Plexiglas partition inside the pool, but, despite this, it was not a fixed structure and one of the sharks managed to pass through it. He had to abandon the pool immediately. Connery was forced to wear a toupee during each of the Bond movies because he had started balding at the age of 17. This didn't prevent Connery from being cast in roles, although it became more noticeable in his later years. In 2005, From Russia with Love was adapted by Electronic Arts into a video game, titled From Russia with Love (2005), which featured all-new voice work by Connery as well as his likeness, and those of several of the film's supporting cast.
        After and during the success of the Bond-films he has maintained a successful career as an actor and has appeared in films, including Alfred Hitchcock's Marnie (1964), The Hill (1965), Murder on the Orient Express (1974), The Man Who Would Be King (1975), The Wind and the Lion (1975), Time Bandits (1981), Highlander (1986), The Name of the Rose (1986), The Untouchables (1987) (which earned him an Oscar for best actor in a supporting role), Indiana Jones and the Last Crusade (1989), The Hunt for Red October (1990), Rising Sun (1993), The Rock (1996), Finding Forrester (2000), and The League of Extraordinary Gentlemen (2003).
        Sean married actress Diane Cilento in 1962 and they had a son, Jason Connery, born on January 11, 1963, he followed in his father's footsteps and also became an actor. The marriage ended in divorce in 1973. In 1975 he married Micheline Roquebrune and they have stayed married, they have no children together. He is also a grandfather. His son, Jason and his ex-wife, actress Mia Sara had a son, Dashiell Quinn Connery, in 1997.`,
    },
    {
      fName: 'Ed',
      lName: 'Harris',
      nick: 'Big Tam',
      birthDate: '1950-10-28',
      info: `By transforming into his characters and pulling the audience in, Ed Harris has earned a reputation as one of the most talented actors of our time.
        Ed Harris was born in Tenafly, New Jersey, to Margaret (Sholl), a travel agent, and Robert Lee Harris, a bookstore worker who also sang professionally. Both of his parents were originally from Oklahoma. Harris grew up as the middle child. After graduating high school, he attended New York's Columbia University, where he played football. After viewing local theater productions, Harris took a sudden interest in acting. He left Columbia, headed to Oklahoma, where his parents were living, and enrolled in the University of Oklahoma's theater department. After graduation, he moved to Los Angeles to find work. He started acting in theater and television guest spots. Harris landed his first leading role in a film in cult-favorite George A. Romero's Knightriders (1981). Two years later, he got his first taste of critical acclaim, playing astronaut John Glenn in The Right Stuff (1983). Also that year, he made his New York stage debut in Sam Shepard's "Fool for Love", a performance that earned him an Obie for Outstanding Actor. Harris' career gathered momentum after that. In 2000, he made his debut as a director in the Oscar-winning film Pollock (2000).`,
    },
  ]));
