exports.seed = knex => knex('Persons')
  .del()
  .then(() => knex.batchInsert('Persons', [
    {
      fName: 'Michael',
      lName: 'Curtiz',
      nick: 'Miska',
      birthDate: '1886-12-24',
      info: 'Curtiz began acting in and then directing films in his native Hungary in 1912. After WWI, he continued his filmmaking career in Austria and Germany and into the early 1920s when he directed films in other countries in Europe. Moving to the US in 1926, he started making films in Hollywood for Warner Bros. and became thoroughly entrenched in the studio system. His films during the 1930s and \'40s encompassed nearly every genre imaginable and some, including Casablanca (1942) and Mildred Pierce (1945), are considered to be film classics. His brilliance waned in the 1950s when he made a number of mediocre films for studios other than Warner. He directed his last film in 1961, a year before his death at 74.',
    },
    {
      fName: 'Julius J.',
      lName: 'Epstein',
      nick: null,
      birthDate: '1909-08-22',
      info: 'Julius J. Epstein was born on August 22, 1909 in New York City, New York, USA. He was a writer and producer, known for Casablanca (1942), Reuben, Reuben (1983) and Pete \'n\' Tillie (1972). He was married to Ann Margot Laszlo and Frances Sage. He died on December 30, 2000 in Los Angeles, California, USA.',
    },
    {
      fName: 'Philip G.',
      lName: 'Epstein',
      nick: null,
      birthDate: '1909-08-22',
      info: `Twin brother of Julius J. Epstein.
        Graduated Penn State University [1931]
        Is the grandfather of Boston Red Sox general manager Theo Epstein (the youngest GM in baseball history, who built the 2004 team than won the first Red Sox World Series victory since 1918, reversing the so-called "curse of the Bambino")
        Is the father of novelist Leslie Epstein ("Pandaemonium", "San Remo Drive")
        Is the grandfather of Anya Epstein and her brother, Boston Red Sox general manager Theo Epstein (the youngest GM in baseball history, who built the 2004 team than won the first Red Sox World Series victory since 1918, reversing the so-called "curse of the Bambino").
        Epstein and brother Julius J. Epstein became the first twins to be awarded Oscars when they won in the writing category for Casablanca (1942).`,
    },
    {
      fName: 'Humphrey',
      lName: 'Bogart',
      nick: 'Bogie',
      birthDate: '1899-01-14',
      info: 'Humphrey DeForest Bogart was born in New York City, New York, to Maud Humphrey, a famed magazine illustrator and suffragette, and Belmont DeForest Bogart, a moderately wealthy surgeon (who was secretly addicted to opium). Bogart was educated at Trinity School, NYC, and was sent to Phillips Academy in Andover, Massachusetts, in preparation for medical studies at Yale. He was expelled from Phillips and joined the U.S. Naval Reserve. From 1920 to 1922, he managed a stage company owned by family friend William A. Brady (the father of actress Alice Brady), performing a variety of tasks at Brady\'s film studio in New York. He then began regular stage performances. Alexander Woollcott described his acting in a 1922 play as inadequate. In 1930, he gained a contract with Fox, his feature film debut in a ten-minute short, Broadway\'s Like That (1930), co-starring Ruth Etting and Joan Blondell. Fox released him after two years. After five years of stage and minor film roles, he had his breakthrough role in The Petrified Forest (1936) from Warner Bros. He won the part over Edward G. Robinson only after the star, Leslie Howard, threatened Warner Bros. that he would quit unless Bogart was given the key role of Duke Mantee, which he had played in the Broadway production with Howard. The film was a major success and led to a long-term contract with Warner Bros. From 1936 to 1940, Bogart appeared in 28 films, usually as a gangster, twice in Westerns and even a horror film. His landmark year was 1941 (often capitalizing on parts George Raft had stupidly rejected) with roles in classics such as High Sierra (1941) and as Sam Spade in one of his most fondly remembered films, The Maltese Falcon (1941). These were followed by Casablanca (1942), The Big Sleep (1946), and Key Largo (1948). Bogart, despite his erratic education, was incredibly well-read and he favored writers and intellectuals within his small circle of friends. In 1947, he joined wife Lauren Bacall and other actors protesting the House Un-American Activities Committee witch hunts. He also formed his own production company, and the next year made The Treasure of the Sierra Madre (1948). Bogie won the best actor Academy Award for The African Queen (1951) and was nominated for Casablanca (1942) and as Captain Queeg in The Caine Mutiny (1954), a film made when he was already seriously ill. He died in his sleep at his Hollywood home following surgeries and a battle with throat cancer.',
    },
    {
      fName: 'Ingrid',
      lName: 'Bergman',
      nick: null,
      birthDate: '1915-08-29',
      info: `Ingrid Bergman was one of the greatest actresses from Hollywood's lamented Golden Era. Her natural and unpretentious beauty and her immense acting talent made her one of the most celebrated figures in the history of American cinema. Bergman is also one of the most Oscar-awarded actresses, tied with Meryl Streep, both second only to Katharine Hepburn.
        Ingrid Bergman was born on August 29, 1915 in Stockholm, Sweden, to a German mother, Frieda Henrietta (Adler), and a Swedish father, Justus Samuel Bergman, an artist and photographer. Her mother died when she was only two and her father died when she was 12. She went to live with an elderly uncle.      
        The woman who would be one of the top stars in Hollywood in the 1940s had decided to become an actress after finishing her formal schooling. She had had a taste of acting at age 17 when she played an uncredited role of a girl standing in line in the Swedish film Landskamp (1932) in 1932 - not much of a beginning for a girl who would be known as "Sweden's illustrious gift to Hollywood." Her parents died when she was just a girl and the uncle she lived with didn't want to stand in the way of Ingrid's dream. The next year she enrolled at the Royal Dramatic Theatre School in Stockholm but decided that stage acting was not for her. It would be three more years before she would have another chance at a film. When she did, it was more than just a bit part. The film in question was The Count of the Old Town (1935), where she had a speaking part as Elsa Edlund. After several films that year that established her as a class actress, Ingrid appeared in Intermezzo (1936) as Anita Hoffman. Luckily for her, American producer David O. Selznick saw it and sent a representative from Selznick International Pictures to gain rights to the story and have Ingrid signed to a contract. Once signed, she came to California and starred in United Artists' 1939 remake of her 1936 film, Intermezzo: A Love Story (1939), reprising her original role. The film was a hit and so was Ingrid.
        Her beauty was unlike anything the movie industry had seen before and her acting was superb. Hollywood was about to find out that they had the most versatile actress the industry had ever seen. Here was a woman who truly cared about the craft she represented. The public fell in love with her. Ingrid was under contract to go back to Sweden to film Only One Night (1939) in 1939 and June Night (1940) in 1940. Back in the US she appeared in three films, all well-received. She made only one film in 1942, but it was the classic Casablanca (1942) opposite Humphrey Bogart.
        Ingrid was choosing her roles well. In 1943 she was nominated for an Academy Award for her role in For Whom the Bell Tolls (1943), the only film she made that year. The critics and public didn't forget her when she made Gaslight (1944) the following year--her role of Paula Alquist got her the Oscar for Best Actress. In 1945 Ingrid played in Spellbound (1945), Saratoga Trunk (1945) and The Bells of St. Mary's (1945), for which she received her third Oscar nomination for her role of Sister Benedict. She made no films in 1947, but bounced back with a fourth nomination for Joan of Arc (1948). In 1949 she went to Italy to film Stromboli, terra di Dio (1950), directed by Roberto Rossellini. She fell in love with him and left her husband, Dr. Peter Lindstrom, and daughter, Pia Lindström. America's "moral guardians" in the press and the pulpits were outraged. She was pregnant and decided to remain in Italy, where her son was born. In 1952 Ingrid had twins, Isotta and Isabella Rossellini, who became an outstanding actress in her own right, as did Pia.
        Ingrid continued to make films in Italy and finally returned to Hollywood in 1956 in the title role in Anastasia (1956), which was filmed in England. For this she won her second Academy Award. She had scarcely missed a beat. Ingrid continued to bounce between Europe and the US making movies, and fine ones at that. A film with Ingrid Bergman was sure to be a quality production. In her final big-screen performance in 1978's Autumn Sonata (1978) she had her final Academy Award nomination. Though she didn't win, many felt it was the most sterling performance of her career. Ingrid retired, but not before she gave an outstanding performance in the mini-series A Woman Called Golda (1982), a film about Israeli prime minister Golda Meir. For this she won an Emmy Award as Best Actress, but, unfortunately, she did not live to see the fruits of her labor.
        Ingrid died from cancer on August 29, 1982, her 67th birthday, in London, England.`,
    },
    {
      fName: 'Paul',
      lName: 'Henreid',
      nick: null,
      birthDate: '1908-01-10',
      info: `Paul Henreid was born Paul Georg Julius Freiherr von Hernreid Ritter von Wasel-Waldingau in Trieste, in the Austro-Hungarian Empire. He was the son of Marie Luise Heilig (Lendecke) and Baron Karl Alphons Hernreid. His father was an aristocratic banker, who was born to a Jewish family whose surname was changed from Hirsch to Hernreid.
        Paul grew up in Vienna and studied at the prestigious Maria Theresa Academy (graduating in 1927) and the Institute of Graphic Arts. For four years, he worked as translator and book designer for a publishing outfit run by Otto Preminger, while training to be an actor at night. Preminger was also a protégé (and managing director) of Max Reinhardt. After attending one of Henreid's acting school performances, Preminger introduced him to the famous stage director and this led to a contract. In 1933, Paul made his debut at the Reinhardt Theatre in "Faust". He subsequently had several leading roles on the stage and appeared in a couple of Austrian films. Paul, like his character Victor Laszlo in Casablanca (1942), was avidly anti-fascist. He accordingly left continental Europe and went to London in 1935, first appearing on stage as Prince Albert in "Victoria the Great" two years later.
        Henreid made his English-speaking motion picture debut in the popular drama Goodbye, Mr. Chips (1939), as the sympathetic German master Max Staefel, who proves to be Chipping's truest friend and ally. After that, however, he became incongruously typecast as Nazi henchmen in Mad Men of Europe (1940) and Night Train to Munich (1940). That year, he moved to the United States (becoming a citizen the following year) and quickly established himself on Broadway with "Flight to the West", as a Ribbentrop-type Nazi consul. His powerful performance led to radio work in the serial "Joyce Jordan-Girl Interne" and a film contract with RKO in 1941.
        This marked a turning point in Paul Henreid's career. He finally escaped the stereotypical Teutonic image and began to play heroic or romantic leads, his first being Joan of Paris (1942), opposite Michèle Morgan, as French RAF pilot Paul Lavallier. Significantly, his next film, Now, Voyager (1942), defined his new screen persona: debonnaire, cultured and genteel, lighting two cigarettes simultaneously, then passing one to Bette Davis. According to Henreid, this legendary (and later often lampooned) scene was almost cut from the film because the director, Irving Rapper, had concerns about it. Next came "Casablanca", where Henreid played the idealistic, sensitive patriot Victor Laszlo; the poorly received Bronte sisters biopic Devotion (1946), as an Irish priest; and a stalwart performance as a Polish count and Ida Lupino's love interest, In Our Time (1944).
        After several dull romantic leads, Henreid reinvented himself yet again. He played a memorably athletic and lively Dutch pirate, the 'Barracuda', in RKO's colourful swashbuckler The Spanish Main (1945). Another of his best later performances was as a sadistic South African commandant in the underrated film noir Rope of Sand (1949), which re-united him with his former "Casablanca" co-stars Peter Lorre and Claude Rains. After the Arabian Technicolor adventure, Thief of Damascus (1952), Henreid's star began to fade. His last noteworthy appearance during the fifties was as an itinerant magician in the oriental extravaganza Siren of Bagdad (1953) . The most memorable of several in-jokes, had Henreid lighting two hookahs (water pipes) for one of his harem girls, spoofing his famous scene from "Now, Voyager".
        Outspoken in his opposition to McCarthyism and adhering to his rights under the First Amendment, he was subsequently blacklisted as a "communist sympathizer" by the House Committee on Un- American Activities. In spite of the damage this did to his career, he re-emerged as a director of second features and television episodes for Screen Gems, Desilu and other companies. In 1957, Alfred Hitchcock (in defiance of the blacklist) hired him to direct several episodes of Alfred Hitchcock Presents (1955). Towards the end of his career, Paul Henreid directed his former "Now, Voyager" co-star Bette Davis in the camp melodrama Dead Ringer (1964) and toured with Agnes Moorehead on stage in a short-lived revival of "Don Juan in Hell"(1972- 73). Henreid died of pneumonia in a Santa Monica hospital in April 1992, after having suffered a stroke. He has the distinction of having not just one but two stars on the Hollywood Walk of Fame, one for his films, and one for his television work.`,
    },
    {
      fName: 'Hal B.',
      lName: 'Wallis',
      nick: null,
      birthDate: '1899-09-14',
      info: 'Legendary producer Hal B. Wallis was born in Chicago and moved to Los Angeles when he was in his early 20s. He got a job managing a theater owned by Warner Bros., and his success at the job caught the eye of studio head Jack L. Warner, who gave him a job in the studio\'s publicity department. Within a few months Wallis had worked his way up to head of the department. He was named studio manager in 1928 and production manager shortly thereafter, but was pushed aside by another legendary producer, future 20th Century-Fox studio head Darryl F. Zanuck. In 1933 Zanuck left Warner and Wallis moved back to his old position. He oversaw the production of many of Warners\' most famous films, including Little Caesar (1931), I Am a Fugitive from a Chain Gang (1932), Captain Blood (1935), The Adventures of Robin Hood (1938) and Casablanca (1942). In 1944 Wallis left Warner and formed his own production company, and achieved even more success, being responsible for such films as The Rose Tattoo (1955), Becket (1964), and a string of Elvis Presley movies, most of which were economically produced and all of which made a fortune. Wallis\' last picture was the John Wayne western Rooster Cogburn (1975).',
    },
    {
      fName: 'Jack L.',
      lName: 'Warner',
      nick: 'Mr. Warner',
      birthDate: '1892-08-02',
      info: 'With his brothers Harry M. Warner, Albert Warner, and Sam Warner, he founded Warner Bros. Pictures Inc. in 1923. They released the first motion picture with synchronized sound, The Jazz Singer (1927) with Al Jolson. In the 1930s they gave employment to a parade of stars, including Bette Davis, Errol Flynn and Paul Muni, as well as James Cagney, Edward G. Robinson, and a man whose star would eventually rise in the 1940s, Humphrey Bogart. Decades later, the firm\'s successor, Warner Communications Inc., merged with Time Inc. to become Time Warner Inc., the world\'s largest media and entertainment company.',
    },
    {
      fName: 'Max',
      lName: 'Steiner',
      nick: 'Mr. Warner',
      birthDate: '1888-05-10',
      info: `Austrian composer who achieved legendary status as the creator of hundreds of classic American film scores. As a child he was astonishingly musically gifted, composing complex works as a teenager and completing the course of study at Vienna's Hochschule fuer Musik und Darstellende Kunst in only one year, at the age of sixteen. He studied under Gustav Mahler and, before the age of twenty, made his living as a conductor and as composer of works for the theater, the concert hall, and vaudeville. After a brief sojourn in Britian, Steiner moved to the USA in the same wave as fellow film composer Erich Wolfgang Korngold and quickly became a sought-after orchestrator and conductor on Broadway, bringing the Western classical tradition in which he had been raised to mainstream audiences.      He was soon snatched up by the film studios with the advent of sound and helped the fledgling talkies become musically sophisticated within a brief few years. He was one of the first to fully integrate the musical score with the images on-screen and to score individual scenes for their content and create leitmotifs for individual characters, as opposed to simply providing vaguely appropriate mood music, as evidenced in King Kong (1933), which set the standard for American film music for years to come.
        From the 1930s to the 1960s, he was one of the most respected, innovative, and brilliant composers of American film music, creating a truly staggering number of exceptional scores for films of all types. He was nominated for Academy Awards for his scores eighteen times and won three times. Years after his death in 1971, he remains one of the giants of motion picture history, and his music still thrives.`,
    },

    {
      fName: 'John',
      lName: 'Woo',
      nick: null,
      birthDate: '1946-09-22',
      info: 'Born in southern China, John Woo grew up in Hong Kong, where he began his film career as an assistant director in 1969, working for Shaw Brothers Studios. He directed his first feature in 1973 and has been a prolific director ever since, working in a wide variety of genres before A Better Tomorrow (1986) established his reputation as a master stylist specializing in ultra-violent gangster films and thrillers, with hugely elaborate action scenes shot with breathtaking panache. After gaining a cult reputation in the US with The Killer (1989), Woo was offered a Hollywood contract. He now works in the US.',
    },
    {
      fName: 'Mike',
      lName: 'Werb',
      nick: null,
      birthDate: null,
      info: `A Los Angeles native, Mike Werb received his undergraduate degrees from Stanford, where he majored in one thing after another. He put his costly education to use by joining a New Wave garage band that never left the garage. Turning to writing, he began a burlesque climb up the well-greased Hollywood ladder by entering the UCLA Master's program in screenwriting. He has since worked for every major studio.
        Mike's big break was writing the screenplay for the Jim Carrey comedy "The Mask," but he also embraces his other produced credits, including "Darkman 3: Die, Darkman, Die!," and the giant-rats-attack-a-college-campus epic "Gnaw: The Food of the Gods, Part 2."
        Mike co-wrote and co-produced (with Michael Colleary) the action-thriller "Face/Off," directed by John Woo and starring John Travolta and Nicolas Cage. The New York Times lauded the Oscar-nominated film as "one the 1,000 greatest movies of all time," and Face/Off won the 1997 Best Screenplay statuette at the 24th annual Saturn Awards.
        21st century accomplishments include being one of six credited screenwriters on "Lara Croft: Tomb Raider" starring Angelina Jolie, and the WB's flashy flop TV series "Tarzan" starring Travis Fimmel's abs. Werb and Colleary also worked intimately with Arnold Schwarzenegger on "Collateral Damage," his last major motion picture before becoming Governor of California.
        Recent film credits include the well-reviewed animated hit "Curious George" (Universal/Imagine) and the family comedy "Firehouse Dog" (New Regency/Fox). Werb and Colleary are developing "Prophets of the Ghost Ants" with author Clark Carlton, Lawrence Bender/A Band Apart and director Conrad Vernon ("Monsters v. Aliens").
        Mike also wrote the nano-tech action pilot "Flyswatters" for the SyFy Channel which he will executive produce with Darren Star ("Sex and the City") should it ever go into production.
        He is currently working on "Unnatural History" -- a live-action-adventure series for Warner Horizon and the Cartoon Network.
        Mike is a member of the Academy of Motion Picture Arts and Sciences, the Writers Guild of America and a nominating-committee member of the Academy of Science Fiction, Fantasy and Horror.`,
    },
    {
      fName: 'Micheal',
      lName: 'Colleary',
      nick: null,
      birthDate: null,
      info: 'Michael Colleary is a writer and producer, known for Face/Off (1997), Lara Croft: Tomb Raider (2001) and Unnatural History (2010).',
    },
    {
      fName: 'Terence',
      lName: 'Chang',
      nick: null,
      birthDate: null,
      info: 'Terence Chang is a producer, known for Paycheck (2003), Face/Off (1997) and Warriors of the Rainbow: Seediq Bale I (2011).',
    },
    {
      fName: 'John',
      lName: 'Powell',
      nick: null,
      birthDate: '1963-09-18',
      info: 'John Powell was born on September 18, 1963 in London, England. He is a composer, known for How to Train Your Dragon (2010), Rio (2011) and The Bourne Identity (2002). He was previously married to Melinda Lerner.',
    },
    {
      fName: 'John',
      lName: 'Travolta',
      nick: null,
      birthDate: '1954-02-18',
      info: `John Joseph Travolta was born in Englewood, New Jersey, one of six children of Helen Travolta (née Helen Cecilia Burke) and Salvatore/Samuel J. Travolta. His father was of Italian descent and his mother was of Irish ancestry. His father owned a tire repair shop called Travolta Tires in Hillsdale, NJ. Travolta started acting appearing in a local production of "Who'll Save the Plowboy?". His mother, herself an actress and dancer, enrolled him in a drama school in New York, where he studied voice, dancing and acting. He decided to combine all three of these skills and become a musical comedy performer. At 16 he landed his first professional job in a summer stock production of the musical "Bye Bye Birdie". He quit school at 16 and moved to New York, and worked regularly in summer stock and on television commercials. When work became scarce in New York, he went to Hollywood and appeared in minor roles in several series. A role in the national touring company of the hit 1950s musical "Grease" brought him back to New York. An opening in the New York production of "Grease" gave him his first Broadway role at age 18. After "Grease", he became a member of the company of the Broadway show "Over Here", which starred The Andrews Sisters. After ten months in "Over Here", he decided to try Hollywood once again. Once back in Hollywood, he had little trouble getting roles in numerous television shows. He was seen on The Rookies (1972), Emergency! (1972) and Medical Center (1969) and also made a movie, The Devil's Rain (1975), which was shot in New Mexico. The day he returned to Hollywood from New Mexico, he was called to an audition for a new situation comedy series ABC was planning to produce called Welcome Back, Kotter (1975). He got the part of Vinnie Barbarino and the series went on the air during the 1975 fall season.
        He starred in a number of monumental films, earning his first Oscar and Golden Globe nominations for his role in the blockbuster Saturday Night Fever (1977), which launched the disco phenomenon in the 1970s. He went on to star in the big-screen version of the long-running musical Grease (1978) and the wildly successful Urban Cowboy (1980), which also influenced trends in popular culture. Additional film credits include the Brian De Palma thrillers Carrie (1976) and Blow Out (1981), as well as Amy Heckerling's hit comedy Look Who's Talking (1989) and Nora Ephron's comic hit Michael (1996). Travolta starred in Phenomenon (1996) and took an equally distinctive turn as an action star in John Woo's top-grossing Broken Arrow (1996). He also starred in the classic Face/Off (1997) opposite Nicolas Cage, and The General's Daughter (1999), co-starring Madeleine Stowe. In 2005, Travolta reprised the role of ultra cool Chili Palmer in the Get Shorty (1995) sequel Be Cool (2005). In addition, he starred opposite Scarlett Johansson in the critically-acclaimed independent feature film A Love Song for Bobby Long (2004), which was screened at the Venice Film Festival, where both Travolta and the films won rave reviews. In February 2011, John was honored by Europe's leading weekly program magazine HORZU, with the prestigious Golden Camera Award for "Best Actor International" in Berlin, Germany. Other recent feature film credits include box-office hit-comedy "Wild Hogs", the action-thriller Ladder 49 (2004), the movie version of the successful comic book The Punisher (2004), the drama Basic (2003), the psychological thriller Domestic Disturbance (2001), the hit action picture Swordfish (2001), the infamous sci-fi movie Battlefield Earth (2000), based upon the best-selling novel by L. Ron Hubbard, and Lonely Hearts (2006).
        Travolta has been honored twice with Academy Award nominations, the latest for his riveting portrayal of a philosophical hit-man in Quentin Tarantino's Pulp Fiction (1994). He also received BAFTA and Golden Globe nominations for this highly-acclaimed role and was named Best Actor by the Los Angeles Film Critics Association, among other distinguished awards. Travolta garnered further praise as a Mafioso-turned-movie producer in the comedy sensation Get Shorty (1995), winning the Golden Globe Award for Best Actor in a Motion Picture, Musical or Comedy. In 1998, Travolta was honored by the British Academy of Film and Television Arts with the Britanna Award: and in that same year he received the Lifetime Achievement Award at the Chicago Film Festival. Travolta also won the prestigious Alan J. Pakula Award from the US Broadcast Critics Association for his performance in A Civil Action (1998), based on the best-selling book and directed by Steven Zaillian. He was nominated again for a Golden Globe for his performance in Primary Colors (1998), directed by Mike Nichols and co-starring Emma Thompson and Billy Bob Thornton, and in 2008, he received his sixth Golden Globe nomination for his role as "Edna Turnblad" in the big-screen, box-office hit, Hairspray (2007). As a result of this performance, the Chicago Film Critics and the Santa Barbara Film Festival decided to recognize Travolta with a Lifetime Achievement Award for his role.
        In addition, Travolta starred opposite Denzel Washington in Tony Scott's remake The Taking of Pelham 123 (2009), and he provided the voice of the lead character in Walt Disney Pictures' animated hit Bolt (2008), which was nominated for a 2009 Academy Award for Best Animated Feature Film and a Golden Globe for Best Animated Film, in addition to Best Song for John and Miley Cyrus' duet titled, "I Thought I Lost You".
        Next, Travolta starred in Walt Disney Pictures' Old Dogs (2009), along with Robin Williams, Kelly Preston and Ella Bleu Travolta, followed by the action thriller З Парижу з любов'ю (2010), starring opposite Jonathan Rhys Meyers. In 2012, John starred alongside Taylor Kitsch, Blake Lively, Aaron Taylor-Johnson, Benicio Del Toro, Salma Hayek, Emile Hirsch and Demián Bichir in Oliver Stone's, Savages (2012). The film was based on Don Winslow's best-selling crime novel that was named one of The New York Times' Top 10 Books of 2010. John was most recently seen in Killing Season (2013), co-starring Robert De Niro, and directed by Mark Steven Johnson. John recently completed production on the Boston-based film, The Forger (2014), alongside Academy Award winner Christopher Plummer and Critic's Choice nominee Tye Sheridan. John plays a second-generation petty thief who arranges to get out of prison to spend time with his ailing son (Sheridan) by taking on a job with his father (Plummer) to pay back the syndicate that arranged his release. John has received 2 prestigious aviation awards: in 2003, the American Institute of Aeronautics and Astronautics Foundation Award for Excellence for his efforts to promote commercial flying, and, in 2007, The Living Legends Ambassador of Aviation award.
        John holds 11 jet licenses: 747, 707, Gulfstream II, Lear 24, Hawker 1251A, Eclipse Jet, Vampire Jet, Canadair CL-141 Jet, Soko Jet, Citation ISP and Challenger. Travolta is the Qantas Airways Global Goodwill "Ambassador-at-Large" and piloted the original Qantas 707 during "Spirit of Friendship" global tour in July/August 2002. John is also a business aircraft brand ambassador for Learjet, Challenger and Global jets for the world's leading business aircraft manufacturer, Bombardier. John flew the 707 to New Orleans after the 2005 hurricane disaster bringing food and medical supplies, and in 2010, again flew the 707, this time to Haiti after the earthquake, carrying supplies, doctors and volunteers.
        John, along with his wife, actress Kelly Preston, are also very involved in their charity, The Jett Travolta Foundation, which raises money for children with educational needs.`,
    },
    {
      fName: 'Nicolas',
      lName: 'Cage',
      nick: 'Nick',
      birthDate: '1964-01-07',
      info: `Nicolas Cage was born Nicolas Kim Coppola in Long Beach, California, the son of comparative literature professor August Coppola (whose brother is director Francis Ford Coppola) and dancer/choreographer Joy Vogelsang. He is of Italian (father) and Polish, German, and English (mother) descent. Cage changed his name early in his career to make his own reputation, succeeding brilliantly with a host of classic, quirky roles by the late 1980s.
        Initially studying theatre at Beverly Hills High School (though he dropped out at seventeen), he secured a bit part in Fast Times at Ridgemont High (1982) -- most of which was cut, dashing his hopes and leading to a job selling popcorn at the Fairfax Theater, thinking that would be the only route to a movie career. But a job reading lines with actors auditioning for uncle Francis' Rumble Fish (1983) landed him a role in that film, followed by the punk-rocker in Valley Girl (1983), which was released first and truly launched his career.
        His one-time passion for method acting reached a personal limit when he smashed a street-vendor's remote-control car to achieve the sense of rage needed for his gangster character in The Cotton Club (1984).
        In his early 20s, he dated Jenny Wright for two years and later linked to Uma Thurman. After a relationship of several years with Christina Fulton, a model, they split amicably and share custody of a son, Weston Cage (b.1992). In 2004, he married Alice Kim Cage, with whom he has a son.`,
    },
  ]));
