exports.seed = knex => knex('Persons')
  .del()
  .then(() => knex.batchInsert('Persons', [
    {
      fName: 'Michael',
      lName: 'Curtiz',
      nick: 'Miska',
      birthDate: '1886-12-24',
      info: 'Curtiz began acting in and then directing films in his native Hungary in 1912. After WWI, he continued his filmmaking career in Austria and Germany and into the early 1920s when he directed films in other countries in Europe. Moving to the US in 1926, he started making films in Hollywood for Warner Bros. and became thoroughly entrenched in the studio system. His films during the 1930s and \'40s encompassed nearly every genre imaginable and some, including Casablanca (1942) and Mildred Pierce (1945), are considered to be film classics. His brilliance waned in the 1950s when he made a number of mediocre films for studios other than Warner. He directed his last film in 1961, a year before his death at 74.',
    },
    {
      fName: 'Julius J.',
      lName: 'Epstein',
      nick: null,
      birthDate: '1909-08-22',
      info: 'Julius J. Epstein was born on August 22, 1909 in New York City, New York, USA. He was a writer and producer, known for Casablanca (1942), Reuben, Reuben (1983) and Pete \'n\' Tillie (1972). He was married to Ann Margot Laszlo and Frances Sage. He died on December 30, 2000 in Los Angeles, California, USA.',
    },
    {
      fName: 'Philip G.',
      lName: 'Epstein',
      nick: null,
      birthDate: '1909-08-22',
      info: `Twin brother of Julius J. Epstein.
        Graduated Penn State University [1931]
        Is the grandfather of Boston Red Sox general manager Theo Epstein (the youngest GM in baseball history, who built the 2004 team than won the first Red Sox World Series victory since 1918, reversing the so-called "curse of the Bambino")
        Is the father of novelist Leslie Epstein ("Pandaemonium", "San Remo Drive")
        Is the grandfather of Anya Epstein and her brother, Boston Red Sox general manager Theo Epstein (the youngest GM in baseball history, who built the 2004 team than won the first Red Sox World Series victory since 1918, reversing the so-called "curse of the Bambino").
        Epstein and brother Julius J. Epstein became the first twins to be awarded Oscars when they won in the writing category for Casablanca (1942).`,
    },
    {
      fName: 'Humphrey',
      lName: 'Bogart',
      nick: 'Bogie',
      birthDate: '1899-01-14',
      info: 'Humphrey DeForest Bogart was born in New York City, New York, to Maud Humphrey, a famed magazine illustrator and suffragette, and Belmont DeForest Bogart, a moderately wealthy surgeon (who was secretly addicted to opium). Bogart was educated at Trinity School, NYC, and was sent to Phillips Academy in Andover, Massachusetts, in preparation for medical studies at Yale. He was expelled from Phillips and joined the U.S. Naval Reserve. From 1920 to 1922, he managed a stage company owned by family friend William A. Brady (the father of actress Alice Brady), performing a variety of tasks at Brady\'s film studio in New York. He then began regular stage performances. Alexander Woollcott described his acting in a 1922 play as inadequate. In 1930, he gained a contract with Fox, his feature film debut in a ten-minute short, Broadway\'s Like That (1930), co-starring Ruth Etting and Joan Blondell. Fox released him after two years. After five years of stage and minor film roles, he had his breakthrough role in The Petrified Forest (1936) from Warner Bros. He won the part over Edward G. Robinson only after the star, Leslie Howard, threatened Warner Bros. that he would quit unless Bogart was given the key role of Duke Mantee, which he had played in the Broadway production with Howard. The film was a major success and led to a long-term contract with Warner Bros. From 1936 to 1940, Bogart appeared in 28 films, usually as a gangster, twice in Westerns and even a horror film. His landmark year was 1941 (often capitalizing on parts George Raft had stupidly rejected) with roles in classics such as High Sierra (1941) and as Sam Spade in one of his most fondly remembered films, The Maltese Falcon (1941). These were followed by Casablanca (1942), The Big Sleep (1946), and Key Largo (1948). Bogart, despite his erratic education, was incredibly well-read and he favored writers and intellectuals within his small circle of friends. In 1947, he joined wife Lauren Bacall and other actors protesting the House Un-American Activities Committee witch hunts. He also formed his own production company, and the next year made The Treasure of the Sierra Madre (1948). Bogie won the best actor Academy Award for The African Queen (1951) and was nominated for Casablanca (1942) and as Captain Queeg in The Caine Mutiny (1954), a film made when he was already seriously ill. He died in his sleep at his Hollywood home following surgeries and a battle with throat cancer.',
    },
    {
      fName: 'Ingrid',
      lName: 'Bergman',
      nick: null,
      birthDate: '1915-08-29',
      info: `Ingrid Bergman was one of the greatest actresses from Hollywood's lamented Golden Era. Her natural and unpretentious beauty and her immense acting talent made her one of the most celebrated figures in the history of American cinema. Bergman is also one of the most Oscar-awarded actresses, tied with Meryl Streep, both second only to Katharine Hepburn.
        Ingrid Bergman was born on August 29, 1915 in Stockholm, Sweden, to a German mother, Frieda Henrietta (Adler), and a Swedish father, Justus Samuel Bergman, an artist and photographer. Her mother died when she was only two and her father died when she was 12. She went to live with an elderly uncle.      
        The woman who would be one of the top stars in Hollywood in the 1940s had decided to become an actress after finishing her formal schooling. She had had a taste of acting at age 17 when she played an uncredited role of a girl standing in line in the Swedish film Landskamp (1932) in 1932 - not much of a beginning for a girl who would be known as "Sweden's illustrious gift to Hollywood." Her parents died when she was just a girl and the uncle she lived with didn't want to stand in the way of Ingrid's dream. The next year she enrolled at the Royal Dramatic Theatre School in Stockholm but decided that stage acting was not for her. It would be three more years before she would have another chance at a film. When she did, it was more than just a bit part. The film in question was The Count of the Old Town (1935), where she had a speaking part as Elsa Edlund. After several films that year that established her as a class actress, Ingrid appeared in Intermezzo (1936) as Anita Hoffman. Luckily for her, American producer David O. Selznick saw it and sent a representative from Selznick International Pictures to gain rights to the story and have Ingrid signed to a contract. Once signed, she came to California and starred in United Artists' 1939 remake of her 1936 film, Intermezzo: A Love Story (1939), reprising her original role. The film was a hit and so was Ingrid.
        Her beauty was unlike anything the movie industry had seen before and her acting was superb. Hollywood was about to find out that they had the most versatile actress the industry had ever seen. Here was a woman who truly cared about the craft she represented. The public fell in love with her. Ingrid was under contract to go back to Sweden to film Only One Night (1939) in 1939 and June Night (1940) in 1940. Back in the US she appeared in three films, all well-received. She made only one film in 1942, but it was the classic Casablanca (1942) opposite Humphrey Bogart.
        Ingrid was choosing her roles well. In 1943 she was nominated for an Academy Award for her role in For Whom the Bell Tolls (1943), the only film she made that year. The critics and public didn't forget her when she made Gaslight (1944) the following year--her role of Paula Alquist got her the Oscar for Best Actress. In 1945 Ingrid played in Spellbound (1945), Saratoga Trunk (1945) and The Bells of St. Mary's (1945), for which she received her third Oscar nomination for her role of Sister Benedict. She made no films in 1947, but bounced back with a fourth nomination for Joan of Arc (1948). In 1949 she went to Italy to film Stromboli, terra di Dio (1950), directed by Roberto Rossellini. She fell in love with him and left her husband, Dr. Peter Lindstrom, and daughter, Pia Lindström. America's "moral guardians" in the press and the pulpits were outraged. She was pregnant and decided to remain in Italy, where her son was born. In 1952 Ingrid had twins, Isotta and Isabella Rossellini, who became an outstanding actress in her own right, as did Pia.
        Ingrid continued to make films in Italy and finally returned to Hollywood in 1956 in the title role in Anastasia (1956), which was filmed in England. For this she won her second Academy Award. She had scarcely missed a beat. Ingrid continued to bounce between Europe and the US making movies, and fine ones at that. A film with Ingrid Bergman was sure to be a quality production. In her final big-screen performance in 1978's Autumn Sonata (1978) she had her final Academy Award nomination. Though she didn't win, many felt it was the most sterling performance of her career. Ingrid retired, but not before she gave an outstanding performance in the mini-series A Woman Called Golda (1982), a film about Israeli prime minister Golda Meir. For this she won an Emmy Award as Best Actress, but, unfortunately, she did not live to see the fruits of her labor.
        Ingrid died from cancer on August 29, 1982, her 67th birthday, in London, England.`,
    },
    {
      fName: 'Paul',
      lName: 'Henreid',
      nick: null,
      birthDate: '1908-01-10',
      info: `Paul Henreid was born Paul Georg Julius Freiherr von Hernreid Ritter von Wasel-Waldingau in Trieste, in the Austro-Hungarian Empire. He was the son of Marie Luise Heilig (Lendecke) and Baron Karl Alphons Hernreid. His father was an aristocratic banker, who was born to a Jewish family whose surname was changed from Hirsch to Hernreid.
        Paul grew up in Vienna and studied at the prestigious Maria Theresa Academy (graduating in 1927) and the Institute of Graphic Arts. For four years, he worked as translator and book designer for a publishing outfit run by Otto Preminger, while training to be an actor at night. Preminger was also a protégé (and managing director) of Max Reinhardt. After attending one of Henreid's acting school performances, Preminger introduced him to the famous stage director and this led to a contract. In 1933, Paul made his debut at the Reinhardt Theatre in "Faust". He subsequently had several leading roles on the stage and appeared in a couple of Austrian films. Paul, like his character Victor Laszlo in Casablanca (1942), was avidly anti-fascist. He accordingly left continental Europe and went to London in 1935, first appearing on stage as Prince Albert in "Victoria the Great" two years later.
        Henreid made his English-speaking motion picture debut in the popular drama Goodbye, Mr. Chips (1939), as the sympathetic German master Max Staefel, who proves to be Chipping's truest friend and ally. After that, however, he became incongruously typecast as Nazi henchmen in Mad Men of Europe (1940) and Night Train to Munich (1940). That year, he moved to the United States (becoming a citizen the following year) and quickly established himself on Broadway with "Flight to the West", as a Ribbentrop-type Nazi consul. His powerful performance led to radio work in the serial "Joyce Jordan-Girl Interne" and a film contract with RKO in 1941.
        This marked a turning point in Paul Henreid's career. He finally escaped the stereotypical Teutonic image and began to play heroic or romantic leads, his first being Joan of Paris (1942), opposite Michèle Morgan, as French RAF pilot Paul Lavallier. Significantly, his next film, Now, Voyager (1942), defined his new screen persona: debonnaire, cultured and genteel, lighting two cigarettes simultaneously, then passing one to Bette Davis. According to Henreid, this legendary (and later often lampooned) scene was almost cut from the film because the director, Irving Rapper, had concerns about it. Next came "Casablanca", where Henreid played the idealistic, sensitive patriot Victor Laszlo; the poorly received Bronte sisters biopic Devotion (1946), as an Irish priest; and a stalwart performance as a Polish count and Ida Lupino's love interest, In Our Time (1944).
        After several dull romantic leads, Henreid reinvented himself yet again. He played a memorably athletic and lively Dutch pirate, the 'Barracuda', in RKO's colourful swashbuckler The Spanish Main (1945). Another of his best later performances was as a sadistic South African commandant in the underrated film noir Rope of Sand (1949), which re-united him with his former "Casablanca" co-stars Peter Lorre and Claude Rains. After the Arabian Technicolor adventure, Thief of Damascus (1952), Henreid's star began to fade. His last noteworthy appearance during the fifties was as an itinerant magician in the oriental extravaganza Siren of Bagdad (1953) . The most memorable of several in-jokes, had Henreid lighting two hookahs (water pipes) for one of his harem girls, spoofing his famous scene from "Now, Voyager".
        Outspoken in his opposition to McCarthyism and adhering to his rights under the First Amendment, he was subsequently blacklisted as a "communist sympathizer" by the House Committee on Un- American Activities. In spite of the damage this did to his career, he re-emerged as a director of second features and television episodes for Screen Gems, Desilu and other companies. In 1957, Alfred Hitchcock (in defiance of the blacklist) hired him to direct several episodes of Alfred Hitchcock Presents (1955). Towards the end of his career, Paul Henreid directed his former "Now, Voyager" co-star Bette Davis in the camp melodrama Dead Ringer (1964) and toured with Agnes Moorehead on stage in a short-lived revival of "Don Juan in Hell"(1972- 73). Henreid died of pneumonia in a Santa Monica hospital in April 1992, after having suffered a stroke. He has the distinction of having not just one but two stars on the Hollywood Walk of Fame, one for his films, and one for his television work.`,
    },
    {
      fName: 'Hal B.',
      lName: 'Wallis',
      nick: null,
      birthDate: '1899-09-14',
      info: 'Legendary producer Hal B. Wallis was born in Chicago and moved to Los Angeles when he was in his early 20s. He got a job managing a theater owned by Warner Bros., and his success at the job caught the eye of studio head Jack L. Warner, who gave him a job in the studio\'s publicity department. Within a few months Wallis had worked his way up to head of the department. He was named studio manager in 1928 and production manager shortly thereafter, but was pushed aside by another legendary producer, future 20th Century-Fox studio head Darryl F. Zanuck. In 1933 Zanuck left Warner and Wallis moved back to his old position. He oversaw the production of many of Warners\' most famous films, including Little Caesar (1931), I Am a Fugitive from a Chain Gang (1932), Captain Blood (1935), The Adventures of Robin Hood (1938) and Casablanca (1942). In 1944 Wallis left Warner and formed his own production company, and achieved even more success, being responsible for such films as The Rose Tattoo (1955), Becket (1964), and a string of Elvis Presley movies, most of which were economically produced and all of which made a fortune. Wallis\' last picture was the John Wayne western Rooster Cogburn (1975).',
    },
    {
      fName: 'Jack L.',
      lName: 'Warner',
      nick: 'Mr. Warner',
      birthDate: '1892-08-02',
      info: 'With his brothers Harry M. Warner, Albert Warner, and Sam Warner, he founded Warner Bros. Pictures Inc. in 1923. They released the first motion picture with synchronized sound, The Jazz Singer (1927) with Al Jolson. In the 1930s they gave employment to a parade of stars, including Bette Davis, Errol Flynn and Paul Muni, as well as James Cagney, Edward G. Robinson, and a man whose star would eventually rise in the 1940s, Humphrey Bogart. Decades later, the firm\'s successor, Warner Communications Inc., merged with Time Inc. to become Time Warner Inc., the world\'s largest media and entertainment company.',
    },
    {
      fName: 'JMax',
      lName: 'Steiner',
      nick: 'Mr. Warner',
      birthDate: '1888-05-10',
      info: `Austrian composer who achieved legendary status as the creator of hundreds of classic American film scores. As a child he was astonishingly musically gifted, composing complex works as a teenager and completing the course of study at Vienna's Hochschule fuer Musik und Darstellende Kunst in only one year, at the age of sixteen. He studied under Gustav Mahler and, before the age of twenty, made his living as a conductor and as composer of works for the theater, the concert hall, and vaudeville. After a brief sojourn in Britian, Steiner moved to the USA in the same wave as fellow film composer Erich Wolfgang Korngold and quickly became a sought-after orchestrator and conductor on Broadway, bringing the Western classical tradition in which he had been raised to mainstream audiences.      He was soon snatched up by the film studios with the advent of sound and helped the fledgling talkies become musically sophisticated within a brief few years. He was one of the first to fully integrate the musical score with the images on-screen and to score individual scenes for their content and create leitmotifs for individual characters, as opposed to simply providing vaguely appropriate mood music, as evidenced in King Kong (1933), which set the standard for American film music for years to come.
        From the 1930s to the 1960s, he was one of the most respected, innovative, and brilliant composers of American film music, creating a truly staggering number of exceptional scores for films of all types. He was nominated for Academy Awards for his scores eighteen times and won three times. Years after his death in 1971, he remains one of the giants of motion picture history, and his music still thrives.`,
    },
  ]));
